### ISSUE TITLE
Send marker for entries

### ISSUE THREAD

**Issue by TuxUbuntu** [dignifiedquire/async-tar#3]
Send market isn't implement for entries.

```rust
use tokio::fs::File;
use tokio_tar::Archive;
use futures::prelude::*;
use tokio::prelude::*;

#[tokio::main]
async fn main() {
	tokio::spawn(async {
		let file = File::open("/dev/null").await.unwrap();
		let mut a = Archive::new(file);
		let mut entries = a.entries().unwrap();
		entries.next().await;
	});
}
```
Dependencies:

```toml
tokio-tar = "0.1.0" # or async-tar = "0.1.1"
futures = "0.3.4"
tokio = { version = "0.2.13", features = ["full"] }
```
